steps:

- id: build-image
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/build:$BUILD_ID', '.' ]

- id: build
  waitFor:
  - build-image
  name: 'eu.gcr.io/$PROJECT_ID/build:$BUILD_ID'
  entrypoint: "/bin/bash"
  args:
  - -c
  - |
    mkdir build
    k8sref docbook > build/k8s-api.xml
    mkdir -p website/content/en/docs
    k8sref md website/content/en/docs
    make pdf
    make pdf FORMAT=A4

- id: hugo
  waitFor:
  - build
  name: 'klakegg/hugo'
  entrypoint: "/bin/sh"
  args:
  - -c
  - |
    cd website
    hugo --environment ${_HOSTING}
    tar zcf public.tgz public

- id: deploy
  waitFor: ['hugo']
  name: 'eu.gcr.io/$PROJECT_ID/firebase'
  args: 
  - 'deploy'
  - '-P'
  - '$PROJECT_ID'
  - '--only'
  - 'hosting:${_HOSTING}'
  dir: website

artifacts:
  objects:
    location: 'gs://$PROJECT_ID/${BRANCH_NAME}${TAG_NAME}/'
    paths:
    - "build/k8s-api.xml"
    - "build/pdf-USletter/k8s-api-USletter.pdf"
    - "build/pdf-A4/k8s-api-A4.pdf"
    - "website/public.tgz"
