example_location: "examples"
resource_categories:
  - name: "Category 1"
    resources:
    - name: Definition1
      version: v1
      group: core
      goimport: "k8s.io/api/core/v1"
      field_categories:
      - definition: Definition1Spec
        list:
        - fields:
          - name: name
        - name: Spec fields
          fields:
          - name: aspecprop1
            depth: -1
          - name: aspecprop2
